## Traer todos los productos

GET http://localhost:3000/productos/

### Para crear un prodcuto
POST http://localhost:4321/productos
Content-Type: application/json

{
    "id": 10,
    "nombre": "Lipgloss hidratante",
    "coleccion": "GlossyGlow",
    "precio": "25000",
    "src": "/images/8.png",
    "descripcion": "Lipgloss hidratante que proporciona un brillo intenso y duradero a tus labios. Enriquecido con ingredientes hidratantes como el aceite de jojoba y la manteca de karité, este gloss deja los labios suaves, flexibles y completamente hidratados. Disponible en una variedad de tonos y acabados para complementar cualquier look.",
    "calificacion": "4.7",
    "categoria": "Maquillaje",
    "subcategoria": "Labios",
    "uso": "Aplica una capa uniforme de lipgloss sobre los labios limpios y secos. Puedes usarlo solo para un toque de brillo sutil o sobre tu labial favorito para intensificar el color y agregar un acabado brillante. Reaplica según sea necesario para mantener tus labios hidratados y con un brillo hermoso.",
    "stock": "700",
    "tag_list": [
        "Vegano",
        "Libre de crueldad animal",
        "Hidratante",
        "Brillo intenso"
    ],
    "colores": [
        {
            "hex": "#FFC0CB",
            "nombre": "Cotton Candy"
        },
        {
            "hex": "#FF4500",
            "nombre": "Tangerine Dream"
        },
        {
            "hex": "#FFD700",
            "nombre": "Golden Glow"
        }
    ]
}
